name: Docker Tag Generator to GHCR

on:
  workflow_dispatch: # Permet de lancer manuellement cette action.
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      - name: Tag Docker image with various versions
        run: |
          # Convertir le nom du repository en minuscules
          REPO_NAME=${{ github.repository_owner,, }}
          
          # Tags pour le format spécifique
          docker tag my-image:latest ghcr.io/$REPO_NAME/php:8.1-ubi9-caddy8.4.2-oci8.3
          docker tag my-image:latest ghcr.io/$REPO_NAME/php:8.2-ubi9-caddy8.5.0-oci8.4

          # Tags Semver pour tester les mises à jour
          docker tag my-image:latest ghcr.io/$REPO_NAME/php:8.1.0
          docker tag my-image:latest ghcr.io/$REPO_NAME/php:8.1.1

      - name: Push Docker tags
        run: |
          # Convertir le nom du repository en minuscules
          REPO_NAME=${{ github.repository_owner,, }}
          
          docker push ghcr.io/$REPO_NAME/php:8.1-ubi9-caddy8.4.2-oci8.3
          docker push ghcr.io/$REPO_NAME/php:8.2-ubi9-caddy8.5.0-oci8.4

          docker push ghcr.io/$REPO_NAME/php:8.1.0
          docker push ghcr.io/$REPO_NAME/php:8.1.1
